### ISSUE TITLE
No Bus timetable

### ISSUE THREAD

**Issue by kylow-may** [bremor/public_transport_victoria#11]
When I tried to load the PTV bus timetables, it goes into a loop.

**Comment by bremor** [comment]
Thanks for raising this issue! Before I take a look is there anything in your logs when you try this?

**Comment by kylow-may** [comment]
It says time out...

Traceback (most recent call last):
  File "/config/custom_components/public_transport_victoria/config_flow.py", line 66, in async_step_route_types
    self.routes = await self.connector.async_routes(
  File "/config/custom_components/public_transport_victoria/PublicTransportVictoria/public_transport_victoria.py", line 73, in async_routes
    response = await response.json()
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1094, in json
    await self.read()
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1034, in read
    self._body = await self.content.read()
  File "/usr/local/lib/python3.8/site-packages/aiohttp/streams.py", line 371, in read
    block = await self.readany()
  File "/usr/local/lib/python3.8/site-packages/aiohttp/streams.py", line 393, in readany
    await self._wait("readany")
  File "/usr/local/lib/python3.8/site-packages/aiohttp/streams.py", line 307, in _wait
    await waiter
  File "/usr/local/lib/python3.8/site-packages/aiohttp/helpers.py", line 656, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError

**Comment by bremor** [comment]
Thanks, I was able to replicate the issue, but then it magically started working, so i'm not sure what's going on here.
I have released a new verison which has additional debugging information which will help us troubleshoot if this happens again.

**Comment by bremor** [comment]
I have discovered the list of bus routes is huge. The response from the PTV API is 188,000 characters long... I think the python code is having issues with the large response. If you keep trying 3-4 times it might just fix it and allow you to set up this integration.

**Comment by bremor** [comment]
Closing this issue, feel free to reopen if you keep having this issue.

**Comment by kylow-may** [comment]
Issue kept surfacing again. I didn't look at it until now. The bus time tables are not loadable at all. Kept failing from time to time.

**Comment by kylow-may** [comment]
Is it possible to extend the timeout and the download size. Got a feeling it is the reason for the intermittent failure and the need to retry multiple times to get the data.

**Comment by kylow-may** [comment]
And it is possible to have the bus number instead of that long description. Sometimes I cannot tell the bus number from the description.

**Comment by yalexau** [comment]
Can confirm a timeout error is occurring on bus networks, is there a way to increase the timeout?

**Comment by catatonicChimp** [comment]
Is this still an issue? Seems to work ok here, but I agree we do need to add in route numbers before the route name (in progress)

**Comment by yalexau** [comment]
> Is this still an issue? Seems to work ok here, but I agree we do need to add in route numbers before the route name (in progress)

been working for me so far

**Comment by kylow-may** [comment]
Yes it is. Noticed PTV timetable for buses has not been maintained at all.

**Comment by catatonicChimp** [comment]
Can you give me an example of a route that isn't working?

**Comment by kylow-may** [comment]
Bus route 903, 279, 302 etc. Some works for a short time and then stop
working. Connections have to be deleted and restart again. It happens very
often.

**Comment by catatonicChimp** [comment]
Ok will have a look, but sounds at least on the surface like a ptv data issue, but if that is the case we should still handle that a bit cleaner

In the meantime can you update to the latest release 0.6 (from last night and see if the issue persists)

**Comment by teknetia** [comment]
I’ve been trying to add bus routes and once got it to return a list of routes but then couldn’t filter it and couldn’t find the route I was after. It just gives me an unknown error.

Is there any way to add a filter the request to the API? Like a route number or something to get a more reasonably response?
