### ISSUE TITLE
Trouble on the busses

### ISSUE THREAD

**Issue by OppyLock** [bremor/public_transport_victoria#9]
On setting up the integration, I can add trains ok, but not busses.
Selecting Bus and submitting has the interface spinning for awhile and then this hits the logs.

2020-11-27 14:55:15 ERROR (MainThread) [custom_components.public_transport_victoria.config_flow] Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/public_transport_victoria/config_flow.py", line 66, in async_step_route_types
    self.routes = await self.connector.async_routes(
  File "/config/custom_components/public_transport_victoria/PublicTransportVictoria/public_transport_victoria.py", line 73, in async_routes
    response = await response.json()
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1094, in json
    await self.read()
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1034, in read
    self._body = await self.content.read()
  File "/usr/local/lib/python3.8/site-packages/aiohttp/streams.py", line 371, in read
    block = await self.readany()
  File "/usr/local/lib/python3.8/site-packages/aiohttp/streams.py", line 393, in readany
    await self._wait("readany")
  File "/usr/local/lib/python3.8/site-packages/aiohttp/streams.py", line 307, in _wait
    await waiter
  File "/usr/local/lib/python3.8/site-packages/aiohttp/helpers.py", line 656, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError

**Comment by bremor** [comment]
Thanks mate! I will admit I have done no testing with buses. I will test it myself and figure out what the go is.

Please let me know if there are any suggestions or anything else.. at this stage i'm not sure how many people are actually using this integration so would be good to have some feedback.

**Comment by OppyLock** [comment]
Never mind ... my fault ... I was sending it via a VPN proxy and it didn't like it.  Direct ... no problem.

I had been using a cobbled together GTFS integration to track 3 each way trips on bus, train and v/line.  The family used it all the time when we could travel ;)  This integration will be MUCH lighter on the memory footprint than GTFS is.

**Comment by bremor** [comment]
Yeah, I've been working from home since March so don't need to use this at all 👍
